<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<!-- ✨ Habilita a documentação XML para o Swagger ler: -->
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<!-- Ignora avisos de comentários faltantes em classes simples (warning CS1591) -->
		<NoWarn>$(NoWarn);1591</NoWarn>
	</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc" Version="8.1.0" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.0" />
    <PackageReference Include="AutoMapper" Version="12.0.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="FluentAssertions" Version="6.12.2" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.12" />
    <PackageReference Include="Microsoft.EntityFrameWorkCore" Version="8.0.12" />
    <PackageReference Include="Microsoft.EntityFrameWorkCore.SqlServer" Version="8.0.12" />
    <PackageReference Include="Microsoft.EntityFrameWorkCore.Tools" Version="8.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FinPulse.Application\FinPulse.Application.csproj" />
    <ProjectReference Include="..\FinPulse.Domain\FinPulse.Domain.csproj" />
    <ProjectReference Include="..\FinPulse.Infrastructure\FinPulse.Infrastructure.csproj" />
  </ItemGroup>

</Project>
