// <auto-generated />
using System;
using FinPulse.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinPulse.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260819202150_CriacaoInicialComSeed")]
    partial class CriacaoInicialComSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinPulse.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<string>("Cor")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Icone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            CategoriaId = 1,
                            Cor = "#EF4444",
                            Icone = "utensils",
                            Nome = "Alimentação",
                            Tipo = 1
                        },
                        new
                        {
                            CategoriaId = 2,
                            Cor = "#F97316",
                            Icone = "car",
                            Nome = "Transporte",
                            Tipo = 1
                        },
                        new
                        {
                            CategoriaId = 3,
                            Cor = "#8B5CF6",
                            Icone = "home",
                            Nome = "Moradia",
                            Tipo = 1
                        },
                        new
                        {
                            CategoriaId = 4,
                            Cor = "#EC4899",
                            Icone = "heart-pulse",
                            Nome = "Saúde",
                            Tipo = 1
                        },
                        new
                        {
                            CategoriaId = 5,
                            Cor = "#EAB308",
                            Icone = "gamepad",
                            Nome = "Lazer",
                            Tipo = 1
                        },
                        new
                        {
                            CategoriaId = 6,
                            Cor = "#3B82F6",
                            Icone = "graduation-cap",
                            Nome = "Educação",
                            Tipo = 1
                        },
                        new
                        {
                            CategoriaId = 7,
                            Cor = "#10B981",
                            Icone = "money-bill-wave",
                            Nome = "Salário",
                            Tipo = 0
                        },
                        new
                        {
                            CategoriaId = 8,
                            Cor = "#06B6D4",
                            Icone = "chart-line",
                            Nome = "Investimentos",
                            Tipo = 0
                        },
                        new
                        {
                            CategoriaId = 9,
                            Cor = "#6366F1",
                            Icone = "laptop-code",
                            Nome = "Freelance / Extra",
                            Tipo = 0
                        });
                });

            modelBuilder.Entity("FinPulse.Models.ContaBancaria", b =>
                {
                    b.Property<int>("ContaBancariaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContaBancariaId"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<string>("Banco")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Cor")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Icone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Saldo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("ContaBancariaId");

                    b.ToTable("ContasBancarias");
                });

            modelBuilder.Entity("FinPulse.Models.MetaFinanceira", b =>
                {
                    b.Property<int>("MetaFinanceiraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MetaFinanceiraId"));

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataLimite")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("ValorAlvo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorAtual")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MetaFinanceiraId");

                    b.ToTable("MetasFinanceiras");
                });

            modelBuilder.Entity("FinPulse.Models.Orcamento", b =>
                {
                    b.Property<int>("OrcamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrcamentoId"));

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorGasto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorLimite")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrcamentoId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Orcamentos");
                });

            modelBuilder.Entity("FinPulse.Models.Transacao", b =>
                {
                    b.Property<int>("TransacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransacaoId"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<int>("ContaBancariaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TransacaoId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ContaBancariaId");

                    b.ToTable("Transacoes");
                });

            modelBuilder.Entity("FinPulse.Models.Orcamento", b =>
                {
                    b.HasOne("FinPulse.Models.Categoria", "Categoria")
                        .WithMany("Orcamentos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("FinPulse.Models.Transacao", b =>
                {
                    b.HasOne("FinPulse.Models.Categoria", "Categoria")
                        .WithMany("Transacoes")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinPulse.Models.ContaBancaria", "ContaBancaria")
                        .WithMany("Transacoes")
                        .HasForeignKey("ContaBancariaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("ContaBancaria");
                });

            modelBuilder.Entity("FinPulse.Models.Categoria", b =>
                {
                    b.Navigation("Orcamentos");

                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("FinPulse.Models.ContaBancaria", b =>
                {
                    b.Navigation("Transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
